[CmdletBinding()]
param(
    [string]$KeystorePath = (Join-Path $env:USERPROFILE "AndroidKeys\kanji-trainer-release.jks"),
    [string]$Alias = "kanji-trainer",
    [string]$PropertiesPath = "",
    [string]$DName = "CN=Kanji Trainer, OU=Personal, O=Personal, L=Seoul, S=Seoul, C=KR",
    [int]$ValidityDays = 10000,
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function New-RandomPassword {
    param([int]$Length = 40)

    $chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
    $bytes = New-Object byte[] $Length
    $rng = [System.Security.Cryptography.RNGCryptoServiceProvider]::new()
    try {
        $rng.GetBytes($bytes)
    } finally {
        $rng.Dispose()
    }

    $result = New-Object System.Text.StringBuilder
    foreach ($byte in $bytes) {
        [void]$result.Append($chars[$byte % $chars.Length])
    }
    return $result.ToString()
}

function Find-Keytool {
    $fromPath = Get-Command keytool -ErrorAction SilentlyContinue
    if ($fromPath) {
        return $fromPath.Source
    }

    if ($env:JAVA_HOME) {
        $fromJavaHome = Join-Path $env:JAVA_HOME "bin\keytool.exe"
        if (Test-Path -LiteralPath $fromJavaHome) {
            return $fromJavaHome
        }
    }

    $androidStudioKeytool = "C:\Program Files\Android\Android Studio\jbr\bin\keytool.exe"
    if (Test-Path -LiteralPath $androidStudioKeytool) {
        return $androidStudioKeytool
    }

    throw "keytool.exe was not found. Install Android Studio or set JAVA_HOME to a JDK."
}

if ([string]::IsNullOrWhiteSpace($PropertiesPath)) {
    $PropertiesPath = Join-Path (Split-Path -Parent $PSScriptRoot) "keystore.properties"
}

$keystoreFullPath = [System.IO.Path]::GetFullPath($KeystorePath)
$propertiesFullPath = [System.IO.Path]::GetFullPath($PropertiesPath)

if ((Test-Path -LiteralPath $keystoreFullPath) -and -not $Force) {
    throw "Keystore already exists: $keystoreFullPath. Pass -Force only if you intentionally want to replace it."
}

if ((Test-Path -LiteralPath $propertiesFullPath) -and -not $Force) {
    throw "Properties file already exists: $propertiesFullPath. Pass -Force only if you intentionally want to replace it."
}

$keytool = Find-Keytool
$keystoreDir = Split-Path -Parent $keystoreFullPath
New-Item -ItemType Directory -Force -Path $keystoreDir | Out-Null

$storePassword = New-RandomPassword
$keyPassword = New-RandomPassword

& $keytool `
    -genkeypair `
    -v `
    -keystore $keystoreFullPath `
    -alias $Alias `
    -keyalg RSA `
    -keysize 4096 `
    -validity $ValidityDays `
    -storetype JKS `
    -storepass $storePassword `
    -keypass $keyPassword `
    -dname $DName

if ($LASTEXITCODE -ne 0) {
    throw "keytool failed with exit code $LASTEXITCODE"
}

$storeFileForGradle = $keystoreFullPath.Replace("\", "/")
$propertiesContent = @"
# Local release signing config for Kanji Trainer.
# Generated by scripts/generate-release-keystore.ps1.
# Do not commit this file.
storeFile=$storeFileForGradle
storePassword=$storePassword
keyAlias=$Alias
keyPassword=$keyPassword
"@

Set-Content -LiteralPath $propertiesFullPath -Value $propertiesContent -Encoding UTF8

Write-Host "Created release keystore:"
Write-Host "  $keystoreFullPath"
Write-Host "Created local Gradle signing config:"
Write-Host "  $propertiesFullPath"
Write-Host ""
Write-Host "Keep both files private. Git is configured to ignore keystore.properties and keystore files."
